TestTravelApp/Models/Author.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TestTravelApp.Models
{
    public class Author
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(45, ErrorMessage = "El campo {0} debe tener entre {2} y {1} caracteres", MinimumLength = 2)]
        public string Name { get; set; }

        [Display(Name = "Apellidos")]
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [StringLength(45, ErrorMessage = "El campo {0} debe tener entre {2} y {1} caracteres", MinimumLength = 2)]
        public string LastName { get; set; }

        [NotMapped]
        public string FullName { get { return string.Format("{0} {1}", Name, LastName); } }


        public List<AuthorHasBook> AuthorHasBooks { get; set; }

    }
}

TestTravelApp/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestTravelApp.Data;
using TestTravelApp.Models;

namespace TestTravelApp.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AuthorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Author.Include("AuthorHasBooks.Book").ToListAsync());
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author.Include("AuthorHasBooks.Book")
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            TempData["message"] = "Registro creado correctamente";
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Registro Actualizado correctamente";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        TempData["message"] = "Upps, ocurrió un error intente más tarde";
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var author = await _context.Author.FindAsync(id);
            _context.Author.Remove(author);
            await _context.SaveChangesAsync();
            TempData["message"] = "Registro eliminado correctamente";
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
            return _context.Author.Any(e => e.Id == id);
        }
    }
}

TestTravelApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestTravelApp.Data;
using TestTravelApp.Models;
using TestTravelApp.Models.Views;

namespace TestTravelApp.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Book.Include(b => b.Editorial);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Editorial)
                .FirstOrDefaultAsync(m => m.Isbn == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["EditorialId"] = new SelectList(_context.Editorials, "Id", "Name");
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FullName");
            
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookView book)
        {
            if (ModelState.IsValid)
            {
               

                using (var transaction = _context.Database.BeginTransaction())
                {

                    try
                    {
                        _context.Add(book);
                        await _context.SaveChangesAsync();

                        var authorHasBook = new AuthorHasBook
                        {
                            AuthorId = book.AuthorId,
                            BookIsbn = book.Isbn,
                        };
                        _context.Add(authorHasBook);
                        _context.SaveChanges();
                        transaction.Commit();
                        TempData["message"] = "Registro creado correctamente";
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        TempData["message"] = "Error:" + ex.Message;
                    }
                }
            }
            ViewData["EditorialId"] = new SelectList(_context.Editorials, "Id", "Name", book.EditorialId);
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FullName", book.AuthorId);
            return View(book);
        }

        // GET: Books/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.Include("AuthorHasBooks").Where(a => a.Isbn == id).FirstAsync();
            if (book == null)
            {
                return NotFound();
            }
            var authorHasBooks = book.AuthorHasBooks.FirstOrDefault();
            ViewData["EditorialId"] = new SelectList(_context.Editorials, "Id", "Campus", book.EditorialId);
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FullName", authorHasBooks.AuthorId);

            var bookView = new BookView()
            {
                AuthorId = authorHasBooks.AuthorId,
                Editorial = book.Editorial,
                EditorialId = book.EditorialId,
                Isbn = book.Isbn,
                PageNumbers = book.PageNumbers,
                Sinopsis = book.Sinopsis,
                Title = book.Title,
                AuthorHasBookId = authorHasBooks.AuthorHasBookId,

            };

            return View(bookView);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BookView bookView)
        {
            if (id != bookView.Isbn)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    using (var transaction = _context.Database.BeginTransaction())
                    {

                        try
                        {
                            _context.Update(bookView);
                            await _context.SaveChangesAsync();

                            var authorHasBook = new AuthorHasBook
                            {
                                AuthorId = bookView.AuthorId,
                                BookIsbn = bookView.Isbn,
                                AuthorHasBookId = bookView.AuthorHasBookId
                            };
                            _context.Update(authorHasBook);
                            await _context.SaveChangesAsync();
                            transaction.Commit();
                            TempData["message"] = "Registro editado correctamente";
                            return RedirectToAction(nameof(Index));
                        }
                        catch (Exception ex)
                        {
                            transaction.Rollback();
                            TempData["message"] = "Error:" + ex.Message;
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(bookView.Isbn))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FullName", bookView.AuthorId);
            ViewData["EditorialId"] = new SelectList(_context.Editorials, "Id", "Campus", bookView.EditorialId);
            return View(bookView);
        }

        // GET: Books/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Editorial)
                .FirstOrDefaultAsync(m => m.Isbn == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            _context.Book.Remove(book);
            await _context.SaveChangesAsync();
            TempData["message"] = "Registro eliminado correctamente";
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.Isbn == id);
        }
    }
}

TestTravelApp/Views/Authors/Create.cshtml
@model TestTravelApp.Models.Author

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Nuevo Autor</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Volver</a>

            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestTravelApp/Views/Authors/Delete.cshtml
@model TestTravelApp.Models.Author

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Registro</h1>

<h3>¿Estás segura de que quieres eliminar esto?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">Volver</a>
    </form>
</div>

TestTravelApp/Views/Authors/Details.cshtml
@model TestTravelApp.Models.Author

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles del Autor</h1>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Editar</a> |
    <a asp-action="Index" class="btn btn-danger">Volver</a>


</div>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
</div>



<hr />
<div class="row">
    @if (Model.AuthorHasBooks != null && Model.AuthorHasBooks.Count() > 0)
    {
        <h3>Libros publicados</h3>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.AuthorHasBooks.FirstOrDefault().Book.Isbn)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.AuthorHasBooks.FirstOrDefault().Book.Title)
                    </th>
                   
                    <th>
                        @Html.DisplayNameFor(model => model.AuthorHasBooks.FirstOrDefault().Book.PageNumbers)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.AuthorHasBooks)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Book.Isbn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Book.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Book.PageNumbers)
                    </td>

                    <td>
                        <a asp-action="Edit" asp-controller="Books" asp-route-id="@item.Book.Isbn" class="btn btn-warning ">Editar</a>
                        <a asp-action="Details" asp-controller="Books" asp-route-id="@item.Book.Isbn" class="btn btn-info">Detalle</a>
                        <a asp-action="Delete" asp-controller="Books" asp-route-id="@item.Book.Isbn" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h2>El autor aun no ha publicado libros</h2>
    }
</div>

TestTravelApp/Views/Authors/Edit.cshtml
@model TestTravelApp.Models.Author

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Autor</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Volver</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestTravelApp/Views/Authors/Index.cshtml
@model IEnumerable<TestTravelApp.Models.Author>

@{
    ViewData["Title"] = "Index";
}

<h1>Listado de Autores</h1>

@if (TempData["message"] != null)
{
    <div class="alert alert-warning alert-dismissible fade  show" role="alert">
        @TempData["message"]

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<p>
    <a asp-action="Create" class="btn btn-success">Nuevo Autor</a>
</p>
<div class="row">
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <th>
                       Libros publicados
                    </th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <th>
                        @item.AuthorHasBooks.Count()
                    </th>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Detalle</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <h2>No existen Autores registrados</h2>
    }
</div>